---
# tasks file for kanidm_community.kanidm.kanidm

- name: "Ensure prerequisites are installed"
  ansible.builtin.import_tasks: prerequisites.yml

- name: "Create kanidm service user and group"
  ansible.builtin.import_tasks: users.yml

- name: "Detect version change"
  ansible.builtin.import_tasks: detect-version-change.yml

- name: "Run pre-upgrade database check"
  ansible.builtin.import_tasks: pre-upgrade-check.yml
  when: _kanidm_version_changed | bool

- name: "Install Kanidm"
  ansible.builtin.import_tasks: install.yml

- name: "Configure Kanidm"
  ansible.builtin.import_tasks: configure.yml

- name: "Configure certificates"
  ansible.builtin.import_tasks: certificates.yml
  when: kanidm_certbot_enabled | bool

- name: "Manage Kanidm service"
  ansible.builtin.import_tasks: service.yml
