---
# handlers file for kanidm_community.kanidm.kanidm

- name: "Reload systemd"
  ansible.builtin.systemd:
    daemon_reload: true

- name: "Restart kanidm service"
  ansible.builtin.systemd:
    name: "{{ kanidm_service_name }}"
    state: restarted
    enabled: true
