---
# tasks file for kanidm_community.kanidm.kanidm-unixd

- name: "Set up Kanidm PPA repository"
  ansible.builtin.import_tasks: ppa.yml

- name: "Install kanidm-unixd packages"
  ansible.builtin.import_tasks: install.yml

- name: "Configure kanidm-unixd"
  ansible.builtin.import_tasks: configure.yml

- name: "Manage kanidm-unixd service"
  ansible.builtin.import_tasks: service.yml
