---
# defaults file for kanidm_community.kanidm.kanidm-repo

# Distribution codename (auto-detected if empty)
kanidm_repo_distro_codename: ""

# PPA repository URL
kanidm_repo_url: "https://kanidm.github.io/kanidm_ppa"

# PPA component (stable or nightly)
kanidm_repo_component: "stable"

# APT key settings
kanidm_repo_gpg_key_file: "kanidm_ppa.gpg"
kanidm_repo_gpg_key_dest: "/etc/apt/trusted.gpg.d/kanidm_ppa.gpg"
kanidm_repo_sources_list: "/etc/apt/sources.list.d/kanidm_ppa.list"
